# Generated by Django 5.2.1 on 2025-05-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_event_photo_alter_venue_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('MUSIC', '🎵 Музыка'), ('SPORT', '⚽ Спорт'), ('ART', '🎨 Искусство'), ('FOOD', '🍔 Еда'), ('TECH', '💻 Технологии'), ('BUSINESS', '💼 Бизнес')], default='MUSIC', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
