# Generated by Django 5.2.1 on 2025-05-23 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_options_booking_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг'),
        ),
    ]
