# Generated by Django 5.2.1 on 2025-05-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_event_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
